Use hugo Local to make sure events are set to the correct timezone
xHain-hackspace/xhain-website pull request #68
Opened 2024-03-05 18:10 UTC by SThomasP

2024-03-05 22:55 UTC, xamanu reviewed
Love this - great improvement! And it looks already really good. Just had one comment.

2024-03-05 22:55 UTC, xamanu commented on data/calendar.json
Please add this file back on. Probably a newly generated one with the time information in UTC.

2024-03-05 23:01 UTC, gueldenstone commented on data/calendar.json
Sorry that is on me. I thought it was an artfefact left from the previous PR.

2024-03-05 23:13 UTC, xamanu commented
Another tiny tiny thing: please remove the import statement in the download script and the note in README.md about `pytz`.

2024-03-07 20:14 UTC, gueldenstone commented
Looks great thank you so much for figuring this out!

2024-03-07 20:18 UTC, xamanu approved these changes
Indeed, this is really good stuff. Many thanks!

2024-03-07 20:24 UTC, xamanu requested changes
Sorry found one thing. The current event highlight doesn't seem to work anymore. Easy to spot right now.

2024-03-09 13:40 UTC, xamanu approved these changes
Works well. Thanks a lot!

2024-03-09 13:46 UTC, merged